#!/usr/bin/env bash
# Install and configure HAProxy load balancer

echo -e "Updating and doing some minor checks...\n"

function install() {
        command -v "$1" &> /dev/null

        #shellcheck disable=SC2181
        if [ $? -ne 0 ]; then
                echo -e "       Installing: $1\n"
                sudo apt-get update -y -qq && \
                        sudo apt-get install -y "$1" -qq
                echo -e "\n"
        else
                echo -e "       ${1} is already installed.\n"
        fi
}

install haproxy # install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Updated server configuration with logging enabled
server_config="
global
    log /dev/log local0 info

defaults
    log     global
    option  httplog
    option  dontlognull

  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
    http-request set-header X-Served-By %b
    server 6418-web-01 44.208.163.11:80 check
    server 6418-web-02 54.174.3.116:80 check
"

# Apply the server config to /etc/haproxy/haproxy.cfg using tee
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to start on boot
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy service to apply the changes
sudo systemctl restart haproxy

# Check HAProxy status
sudo systemctl status haproxy.service
