#!/usr/bin/env bash
#install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend kabasingaarsene
     bind *:80
     mode http
     default_backend app

backend app
    balance roundrobin 
    server 6418-web-01 44.208.163.11:80 check
    server 6418-web-02 54.174.3.116:80 check" >> /etc/haprocy/haproxy.cfg

sudo service haproxy restart
